lirantal/dockly

src/dockerUtil.js

Change docker utils to an es6 class
Continuation of https://github.com/lirantal/dockly/pull/28
-
-
-

Feature/Docker Utils support es6

---

Dockerfile
README.md

Fixed #38 
- update node version for dockly
- update docker file to build dockly from CI version

fix(docker): docs update and build dockly from CI version

---

.travis.yml
package.json
src/cli.js

Fix version shown
`dockly 3.2.3 by [object Object]`
-
-
-

fix(version): fix author in version

---

README.md

Fix typo in README.md: "manging" should be "managing"

---

README.md
index.js
package.json

Add node badge, changed node engines in package.json, made the unsupported node version error maroon color
-
-
-

feat: node badge

---

README.md

Add responsible public disclosure badge

docs(badge): add responsible public disclosure badge

---

package.json
src/screen.js
src/widgetsTemplates/help.widget.template.js
widgets/help.widget.js
widgets/toolbar.widget.js

Next to the `-h` cli switch, I thought it would be useful to have an actual help dialog inside dockly.

Add help (h) dialog ✨

---

README.md
package.json

docs(README): project description update

---

README.md

Minor changes to spelling and grammar in the README. 
@lirantal

Fix Spelling/Grammar typos in README

---

src/screen.js
src/widgetsTemplates/help.widget.template.js
src/widgetsTemplates/list.widget.template.js
src/widgetsTemplates/logs.widget.template.js
widgets/containers/containerList.widget.js
widgets/searchInput.widget.js
widgets/toolbar.widget.js

Add capability to filter containers list using auto-complete input box
- add new searchInput widget
- bind it to / for search

feat(searchcontainers): new capability to search containers list

---

src/widgetsTemplates/list.widget.template.js
widgets/searchInput.widget.js

fix(logs): do not append an EOL after each log line captured

---

widgets/actionsMenu.widget.js

fix(actionsMenu): toggle visibility on ESC or M key press

---

.gitignore

Added package-lock.json to .gitignore.

added package-lock.json to .gitignore, fixes #89

---

package.json
yarn.lock

Updating dependencies for security fixes in them

fix: upgrade dependencies for security vulnerabitlies

---

hooks/shell.hook.js

Command "shell" if possible runs the bash.
- `execFileSync` command

/bin/bash support

---

package.json

Fix linting issues on docs/ folder

chore: fix docs/ linting issue

---

docs/src/components/Header.js

Fixed logo file to be placed in assets folder

chore: fix misplaced logo image file

---

.travis.yml

Make use of the `gatsby-cli` in the travis build
- Update .travis.yml

build(gatsby): use gatsby-cli

---

package.json

This PR will prevent publishing files that are not needed at runtime.
Fixes size increase from PR #113
https://packagephobia.now.sh/result?p=dockly

Add `files` key to package.json

---

docs/gatsby-config.js
docs/package.json

Add Google Analytics
- add gatsby plugin for GA

chore: add google analytics

---

Dockerfile

Change in Dockerfile to upgrade Alpine pkgs (fixes https://snyk.io/vuln/SNYK-ALPINE311-GCC-598616)
- add `apk update && apk upgrade` to Dockerfile to resolve issue above

update Dockerfile to upgrade Alpine pkgs

---

codefresh.yml

Codefresh requires now to use an explicit registry directive

build(docker): add required registry to codefresh setup

---

README.md

This may help users to find more specific tool for their needs

README.md: Add Alternatives section

---

README.md

Include package health score from the [Snyk Advisor page for dockly](https://snyk.io/advisor/npm-package/dockly)
- Update the README to add a badge

fix: update README badges to include package health score

---

src/screen.js
src/widgetsTemplates/list.widget.template.js

Fixed issue #124 by destroying and creating the necessary widgets on each view load.
this fixed the memory leak and enable us to use the same keyboard shortcut on different views.
- Added a method to `clearWidgets`
- Added a check to `list.widget.template.js` to check if `searchInput` is present

Fix event emitter memory leak

---

hooks/services.hook.js
src/widgetsTemplates/help.widget.template.js
widgets/toolbar.widget.js

Added the functionally to copy service id.
- Keyboard shortcut to copy service id
- Renamed copy command from `copy container id` to `copy id`
- Update help widget

feat: Added Service Id Copy

---

.github/workflows/main.yml
hooks/services.hook.js
src/widgetsTemplates/logs.widget.template.js
widgets/containers/containerLogs.widget.js
widgets/services/servicesLogs.widget.js

Added the job `lint` to check PR's lint.
- Added job `lint`
- fixed lint errors

ci: Added Lint Check In CI

---

Dockerfile

Ensuring that the docker image uses correct fonts, based on resolution of this issue: https://github.com/yaronn/blessed-contrib/issues/111
- Add relevant ENV variables

fix: enforce correct fonts/locales setup in docker

---

README.md

Added section to FAQ about icons not working in some environments and how to fix it
- Update README

docs: added section to FAQ

---

README.md
src/cli.js
src/dockerUtil.js

Added the ability to connect to remote docker demon
- Added option to costume docker host, port, and protocol
- Updated CLI

feat: Add ability to connect to remote docker demons

---

src/widgetsTemplates/help.widget.template.js
src/widgetsTemplates/info.widget.template.js
src/widgetsTemplates/list.widget.template.js
src/widgetsTemplates/logs.widget.template.js
widgets/actionStatus.widget.js
widgets/actionsMenu.widget.js
widgets/searchInput.widget.js

feat: add vi key bindings support

---

widgets/containers/containerList.widget.js

feat: print port bindings in container list

---

src/widgetsTemplates/list.widget.template.js
widgets/containers/containerList.widget.js

Fix #250
- Add guard rails to check updates and actions on the containerLogs widget before running them

fix: #250 dockly crashes on attempt to display non-existent widget

---

dockerRunScript.sh
src/widgetsTemplates/list.widget.template.js
src/widgetsTemplates/logs.widget.template.js
widgets/toolbar.widget.js

Fix #219
- disable mouse on different widgets

fix: disable mouse from widgets
