lirantal/dockly

Dockerfile, README.md
Added Dockerfile to support building dockly as a standalone container.
Reflected changes in the README file.
=> Dockerizing Dockly

.travis.yml, package.json, yarn.lock
Remove snyk from project and CI because it's being run via GitHub integration now. I *think* this is what you had in mind.
- Remove snyk from npm scripts
- Remove snyk from Travis config
- Update yarn.lock
- Leave .snyk policy file alone
=> chore(snyk): Remove snyk from project and CI

widgets/toolbar.widget.js
Fixed "view mode" toggle option not appearing inside of services mode.
-
-
-
=> fix(toolbar): fix view mode not always existing

widgets/toolbar.widget.js
Makes use of better colors for the list bar
- Change grey color for listbar keys to yellow
=> fix(listbar): shortcut key should use more visible colors

dockerRunScript.sh
Bash is not available in all linux distributions so as described in #57, I propose to use `sh` instead.
=> Use `/bin/sh` instead of `/bin/bash`

hooks/containers.hook.js, widgets/actionStatus.widget.js, widgets/actionsMenu.widget.js
The `actionStatus` widget now properly shows status messages made by different widgets
- Refactor event emitter usage for actionStatus
- Update status messages for stop/restart container and menu actions
=> feat(actionStatus): show status messages for actions

src/widgetsTemplates/list.widget.template.js, widgets/containers/containerList.widget.js
Refreshing the containers list maintains selected item focus
- Remove default sort by container status so it doesn't tamper with selected index
- We keep an internal state to append item instead of recreating the list in indeterministic order
=> feat(containerlist): refreshing maintains selected item focus

hooks/shell.hook.js, lib/TerminalLauncher.js
Fixes #81, #76, #55 
Refactors the shell execution so that it tries to auto-detect terminal apps on both MacOS and Linux and reverts back to opn app's last resort of auto-detecting internally.
=> refactor(shell.hook): auto-detect terminal apps

README.md
Fixes #85
Remove the left over containers when running via Docker.
- Add `--rm` switch to docker commands so that Docker removes the containers once exited.
=> Remove left over containers after running

Dockerfile
The docker image, as it currently exists, does not support ARM systems (e.g. Raspberry Pi) which are resource-constrained and often run headless, accessed via ssh.  This change allows the image to be built on Raspberry Pi (tested on Raspberry Pi 3 B+/Docker version 18.09.0, build 4d60db4) and any other architecture supported by the official Node.js image.
- Change base image from mhart/alpine-node:8 to official node:8 image
- [x ] I added tests
=> feat(Dockerfile): support for ARM/ARM64 architectures

src/widgetsTemplates/list.widget.template.js, src/widgetsTemplates/logs.widget.template.js, widgets/containers/containerList.widget.js, widgets/services/servicesList.widget.js
added functionality to clear the log box of any previous logs on select
- add abstract function & function call to clear log box widget with `list.widget.template.js`
- add `clearItemLogs()` function within `(servicesList|containerList).widget.js` to call log box `clear()` function
- add `clear()` function within `logs.widget.template.js` so we have a clean way to clear the log box content
=> Add functionality to clear the logbox of any previous logs on select

dockerRunScript.sh, hooks/shell.hook.js, package.json
It basically freezes blessedjs (because of execSync), clears console and executes docker command. After interactive console is exitted, console is cleared and blessedjs is forced to redraw whole screen - blessedjs keeps track of changes but my _stdio magic_ causes it to get out of sync. Standard streams are seamlessly inheritted, so it should theoretically work in any terminal and OS - even through SSH. Application is never closed, so application state is untouched. Also, there is no need for separate *.sh script (or Windows equivalent)
It was tested on Windows 10 and partially on Ubuntu (no docker installed, just mounted docker socket so shell couldn't be attached)
- Makes "open shell" feature cross-platform, user-friendly and works with standard stdio, so it should work with any …
=> Seamlessly integrate docker interactive shell with dockly

Dockerfile, hooks/shell.hook.js
Fixes #102
Installing docker fixes the issue. Downside is that it increases image size from 193 to 380 MB, but I think it's a sacrifice worth making for regaining functionality.
Another minor issue is that, at least for me, exec'ed shell does not show the cursor. Didn't look into that long, `stty echo` did not help. Any thoughts?
=> Add 'docker' to image

package.json, yarn.lock
This PR introduces the use of lockfile-lint which aims to alleviate testing of lockfiles for trusted sources and protect against security concerns where malicious users may attempt to inject bad packages through lockfiles.
We lint for:
all resources must be served over HTTPS
allowed hosts are set for 'verdaccio', 'npm', and 'yarn' since all are used within the lockfile. This ensures the build doesn't fail, however I recommend that in later PRs we update those resources to include just one source, say verdaccio to not spread source of origin too much.
- add lockfile-lint dep
- use lockfile-lint in the lint run script
=> feat(lockfile-lint): 🎉 enforce lockfile security

dockerRunScript.sh, hooks/shell.hook.js
Fixes https://github.com/lirantal/dockly/issues/109 by disabling the mouse on the shell being opened and restores it again.
- If OS is win32 leave as is
- Otherwise, run script which disables the mouse on the shell, runs the docker shell command and restores mouse again
=> fix(shell): disable mouse-on-shell

.vscode/launch.json, hooks/containers.hook.js, hooks/services.hook.js, package.json, src/widgetsTemplates/help.widget.template.js, src/widgetsTemplates/list.widget.template.js, widgets/searchInput.widget.js, widgets/toolbar.widget.js
Since international keyboards do not all have '=' on an unshifted key and since you often would want to update the view easily the '=' key is not ideal
- I have changed the refresh key to the 'space' bar. 
- Have added debug action to package.json for easy attach to node
- Added launch.json in .vscode folder for easy debugging from Code
=> feat: Change refresh key to space bar

Dockerfile
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
Node 8 is now end of life as of 31st Dec 2019.
Update docker image to use Node 12 which is LTS branch and supported until 30th Apr 2022
-
-
-
=> Updated dockerfile to node 12 LTS

src/widgetsTemplates/list.widget.template.js, widgets/containers/containerList.widget.js
Fixes #145 
- Container list used the cached containersList object on the widget instead of creating a new one and writing to it.
=> fix(containerlist): containerList used cached data

src/baseWidget.js, src/cli.js, src/themes/styles.js, src/themes/theme.selector.js, src/widgetsTemplates/help.widget.template.js, src/widgetsTemplates/info.widget.template.js, src/widgetsTemplates/list.widget.template.js, src/widgetsTemplates/logs.widget.template.js, widgets/actionStatus.widget.js, widgets/actionsMenu.widget.js, widgets/containers/containerStatus.widget.js, widgets/containers/containerUtilization.widget.js, widgets/containers/containerVsImages.widget.js, widgets/searchInput.widget.js, widgets/services/servicesStatus.widget.js, widgets/services/servicesVsImages.widget.js
Support light theme
- Add `--theme` argument with possible values `light` or `dark` (default)
- Add documentation in `--help` command
Moved the basic styles to a separate file `styles.js` and add a theme selector function to select the style based on the `--theme` argument.
This solution gives the option to add other themes, not just dark and light. To do that, what is required is to add the relevant style in `styles.js` and then add the new style in `theme.selector.js`
```
const themeStyleMap = {
light: lightStyle,
dark: darkStyle
}
```
=> feat(theme): support for light theme

src/widgetsTemplates/logs.widget.template.js, widgets/containers/containerLogs.widget.js, widgets/services/servicesLogs.widget.js
Fix dockly crash when trying to expand services logs
- added a method to `logs.widget.template.js` to get the right log widget from the extended classes
=> Fix: dockly crash on service log expend

hooks/containers.hook.js, hooks/services.hook.js, src/screen.js
fix `tab` not working in service view.
- Added event listener for the screen through hooks to update focus accordingly.
- remove focus updates from the screen class.
=> fix: tab not working in service tab

src/widgetsTemplates/list.widget.template.js, widgets/searchInput.widget.js, widgets/services/servicesList.widget.js, widgets/toolbar.widget.js
Added search in the service view.
- Added `filterList` in service view.
- Added an event emitter in the search widget for when the search finished.
- Added event listener in `list.widget.template.js` to focus on the list when the search finished.
=> fix: search not working in service view

.github/workflows/main.yml
Added a check in the build_docs to make it activate only when pushing to master.
by doing that the job will not fail on forks.
- Added check to build_docs to work only when pushing to master
=> ci: fix build_docs fails in forks

widgets/toolbar.widget.js
Copy id now changes to `copy container id` or `copy image id` depended on the view.
this resolve the discussion in the PR #154
- copy id changes depended on the view.
=> feat: copy id label changes depended on the view

Dockerfile
Always install the docker image with pinned deps from the project rather than resolve in real-time
- Update the RUN directive to include the pinned-deps install phase of yarn
=> fix: build image based on pinned deps in the project

hooks/containers.hook.js, hooks/images.hook.js, hooks/services.hook.js, src/widgetsTemplates/base.hook.template.js
surrounded the `clipboardy.writeSync` function with try-catch
but instead of replicating the code on each hook, I created a `hook.template` class that contains the functionality 
- fixed dockly crash when clipboardy fails
- added `hook.template` class
=> fix: dockly crash when copy to Clipboard fails

Dockerfile, docker-entrypoint.sh
Added the ability to pass dockly's arguments to [lirantal/dockly](https://hub.docker.com/r/lirantal/dockly) docker image without calling dockly explicitly
before
```bash
docker run -it --rm -v /var/run/docker.sock:/other/place/docker.sock lirantal/dockly node index -s /other/place/docker.sock 
```
now
```bash
docker run -it --rm -v /var/run/docker.sock:/other/place/docker.sock lirantal/dockly -s /other/place/docker.sock 
```
- Added the ability to pass dockly docker arguments without calling dockly explicitly
=> feat: allow to pass arguments to docker

widgets/containers/containerList.widget.js
Fixes #205 which breaks the table layout if the docker command has CRLF related control characters in it
=> fix: strip crlf to ensure it doesn't break the table layout

src/widgetsTemplates/info.widget.template.js
Fixes #221 
This PR:
1. Fixes the object depth not being recursive when printing container info
2. Colorizes it
Example:
=> feat: apply full-depth object information printing + colorize output

widgets/images/imageList.widget.js
Fixed a bug where the imageList.widget crashed, due to empty digest or tag on docker images.
-
=> fix: prevent splitting on an undefined value

index.js
Fixes #249 
The toolbar widget (`toolbar.on()`) registers 11 event listeneres which triggers a Node.js memory leak warning:
```sh
erik@WS-91019:~$ dockly
(node:15356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 key listeners added to [myWidget]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
```
There is no actual memory leak however, as it registers exactly 11 key presses for the toolbar.
This PR increases the limit to prevent the internal Node.js warning.
=> fix: increase limit on event listeners warning

widgets/images/imageList.widget.js
When Docker images are created locally, they do not have a digest. The name of the image then should be determined from the tag, but this accesses a non-existent value. Therefore no name is displayed:
This pull request fixes this problem and the Docker image name is correctly displayed on the overview.
- **imageList.widget.js 52**: `image[2]` evaluates undefined and therefore should be changed to `image['RepoTags']`
=> fix: missing name of the Docker image, for locally created images

widgets/containers/containerUtilization.widget.js
CPU cores weren't counting correctly, yielding 0 and no cpu usage was showing up.
- updated the code to count correct cpu cores available from `online_cpus`
=> fix: container utilization wasn't counting cpu cores correctly
